### ISSUE TITLE
Cannot find name 'keof'

### ISSUE THREAD

**Issue by andreagrossetti** [moff/angular2-ladda#13]
After upgrading from 1.0.6 to 1.1.1 I got this error using webpack
`[default] /node_modules/angular2-ladda/module/ladda-config.d.ts:9:20
    Cannot find name 'keyof'.
[default] /node_modules/angular2-ladda/module/ladda-config.d.ts:9:26
    ';' expected.
[default] Checking finished with 2 errors`

**Comment by theodorejb** [comment]
`keyof` [is a new operator in TypeScript 2.1](https://blogs.msdn.microsoft.com/typescript/2016/12/07/announcing-typescript-2-1/#keyof-and-lookup-types). The error should go away if you update your TypeScript dependency to v2.1+.

**Comment by codal-jdave** [comment]
I have "typescript": "2.1.1" can You please help me @theodorejb same issue

**Comment by moff** [comment]
@codal-jdave do you have something in your app that requires TypeScript 2.0? Can you show your package.json?
