### ISSUE TITLE
angular 9 update

### ISSUE THREAD

**Issue by rbalet** [moff/angular2-ladda#45]
After updating from angular 8 to 9
```  
ERROR in Failed to compile entry-point angular2-ladda (main as commonjs) due to compilation errors:
node_modules/angular2-ladda/module/module.js:25:27 - error NG1010: Value at position 
0 in the NgModule.declarations of LaddaModule is not a reference: [object Object]    

25             declarations: [LaddaDirective],
```  
![image](https://user-images.githubusercontent.com/44493964/74106745-d2e78f80-4b71-11ea-916c-a7e1b2ef5bfe.png)

**Comment by theodorejb** [comment]
I just published v3.0.0 with support for Angular 9. Can you try it out and close this issue if the problem is fixed?
